/* eslint-disable @typescript-eslint/no-empty-interface */
// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts`

interface CloudflareEnv {
    SUPABASE_PUBLISHABLE_KEY: string;
    SUPABASE_URL: string;
    SUPABASE_SECRET_KEY: string;
}
